### ISSUE TITLE
trying to use numcpp with VS 2015 - compiler errors

### ISSUE THREAD

**Issue by yalexand** [tknopp/numcpp#1]
Hi Tobias,

I am interested in Radon/FBP transforms for Tomography, so I tried to compile only your example06 and then reuse corresponding parts of code. 
I work on Windows with VS 2015.

There are errors in "array.h" (pasted below), - quite severe - I afraid it isn't compatible.

I can only hope that there exists some "Array.h" library that could replace it for Windows.
Or somehow one can circumvent or fix these lines?

Thanks,
Y.
/Yuriy/

Error	C2100	illegal indirection	
numcpp	
[whatever] \numcpp\numcpp\numcpp\core\array.h	371	

Error	C3861	'__builtin_expect': identifier not found	
numcpp	
[whatever] \numcpp\numcpp\numcpp\core\array.h	374

**Comment by tknopp** [comment]
I am not really working on this project anymore. Indeed the library might not be compatible with VS. I used gcc for the development.

It should be pretty straight forward to use different Array libraries such as Eigen or Blitz++ or Armadillo. You can also simple use 1D C++ arrays allocated with `new` and to the 1D/2D index conversion by hand.

**Comment by yalexand** [comment]
many thanks, I will try to look at it. 
suspected something like this.

sorry for nuisance, just 1 more question if I may, about speed - is your implementation faster or slower than Matlab's radon/fbp?

we like to apply it to really massive data, and that is supposed to be basic version, without GPU or/and special HPC speed-up..

**Comment by tknopp** [comment]
do you really need C/C++?
I use Julia for several years and it will be exactly the same speed as in C

**Comment by yalexand** [comment]
we work for Biology, so we need GUI and OME.tiff support for I/O.. also possibility of CUDA/OpenCV speed-up.
I hate it as well but these are requirements. 
Work was actually done in Matlab some 3 years ago, but now another key requirement is open source..

**Comment by tknopp** [comment]
Ok, so if you already have C/C++ infrastructure than it makes sense sticking with that. For a new project Julia can be a very pleasant solution since it will save you a lot of development time (syntax is like Matlab), it will be as fast as C/C++ and of course Julia has solutions for writing GUIs and loading tiffs. It was the actual reason why I stopped working on numcpp.

**Comment by yalexand** [comment]
does Julia support GPU? in Matlab, all API for that, is two commands. 
If yes, I'd look at it.. and not to forget about radon/fbp.. :)

Another one is "Bioformats" library, so called OME.tiffs, it is extended tiff format, usual isn't enough.
so we look at C/C++ for now, other options are Python and Java, basically I'm trying to choose among these evils. :)

**Comment by tknopp** [comment]
Julia has support for GPU programming. It might not be that simple as in Matlab but if I got it correctly Matlab is not an option anyway. In Julia one can directly call C libraries and Python code so you get full support for these both platforms "for free".

Porting my C++ radon/fbp code would be straight forward since it is actually is based on Matlab.

But anyway, just wanted to make you aware that there is an alternative that gets more and more used in the scientific programming community. Python would certainly also be a good alternative although you would need to use some of the "acceleration" libraries (e.g. cython) to make the code actually fast.

**Comment by yalexand** [comment]
python.. tried to connect to Bioformats once via "javabridge",.. got stuck.

Anyway, so many thanks, - you enlightened my world today. seriously.

BTW another success today was getting eventually "live feed" for my Cardiology project. 
Here, the internal chamber of the heart is mapped through special catheter, by sampling multiple sensors' positions and electrograms (point-wise ECGs), in real time. 
That helps to guide correcting ablations on the surface. 
Lot of DSP, to decide where to shoot.
Matlab GUI with C/C++ driver calling the DLL from StJude Medical (hardware company).
overall 3 months took to code/tune it..

..was nice to have this chat, have good week-end
